### ISSUE TITLE
Script is killed when ran

### ISSUE THREAD

**Issue by davidhealey** [elwizard33/Cyberpanel-Server-Wizard-Cleanup#1]
Hi,

I tried running the script with the command given. This is what I see, any idea?

![image](https://github.com/user-attachments/assets/b5d53bec-1e28-49c1-856f-6eb95ec77ac1)

**Comment by davidhealey** [comment]
Ok I ran these commands, and now I can run the script. I think the malware was blocking it.

```
service redis stop
service redis stop
kill -9 $(pidof kdevtmpfsi)
kill -9 $(pidof kinsing)
rm -f /tmp/kdevtmpfsi ; echo "ALL_GOOD_HERE" > /tmp/kdevtmpfsi
rm -f /var/tmp/kinsing ; echo "ALL_GOOD_HERE" > /var/tmp/kinsing
rm -f /tmp/zzz ; echo "ALL_GOOD_HERE" > /tmp/zzz
rm -f /tmp/zzz.sh ; echo "ALL_GOOD_HERE" > /tmp/zzz.sh
chmod -R go-x /tmp
chmod -R 0777 /tmp/
chmod -R go-x /var/tmp
chmod -R 0777 /var/tmp/
```

**Comment by elwizard33** [comment]
Thanks! I will improve with this, I saw some comments the hackers was also blocking github, I'm still doing some research before releasing an update

**Comment by davidhealey** [comment]
Even after running your script it seems the malware is still present, I'm seeing 100% cpu again.
